#!/usr/bin/env python

"""

Parse a the test runner XML output generated by Check and convert it to the
junit XML format.

usage: check2junitxml.py [-h] [-o OUTPUT_PATH] input_path

"""

import sys
import argparse
import re
import types
import dateutil.parser
import xml.etree.ElementTree as ET

NS_SPLIT_PATTERN = re.compile(ur'\{(.*)\}(.*)$')


def split_ns_from_tag(tag):
    """
    >>> split_ns_from_tag('{http://check.sourceforge.net/ns}testsuites')
    ('http://check.sourceforge.net/ns', 'testsuites')
    >>> split_ns_from_tag('testsuites')
    (None, 'testsuites')
    >>> try:
    ...   split_ns_from_tag(None)
    ... except AssertionError, e:
    ...   print e
    tag can't be None
    >>> try:
    ...   split_ns_from_tag(2)
    ... except AssertionError, e:
    ...   print e
    tag must be a string

    """
    assert tag is not None, "tag can't be None"
    assert type(tag) is types.StringType, "tag must be a string"

    match = re.match(NS_SPLIT_PATTERN, tag)
    if(match):
        return match.groups()
    return (None, tag)


def junit_case_from_check_case(check_case):
    """
    >>> success = ET.XML('''<test result="success" xmlns="http://check.sourceforge.net/ns">
    ...   <path>.</path>
    ...   <fn>ex_xml_output.c:8</fn>
    ...   <id>test_pass</id>
    ...   <description>Core</description>
    ...   <message>Passed</message>
    ... </test>''')
    >>> failure = ET.XML('''<test result="failure" xmlns="http://check.sourceforge.net/ns">
    ...   <path>.</path>
    ...   <fn>ex_xml_output.c:14</fn>
    ...   <id>test_fail</id>
    ...   <description>Core</description>
    ...   <message>Failure</message>
    ... </test>''')
    >>> error = ET.XML('''<test result="error" xmlns="http://check.sourceforge.net/ns">
    ...   <path>.</path>
    ...   <fn>ex_xml_output.c:18</fn>
    ...   <id>test_exit</id>
    ...   <description>Core</description>
    ...   <message>Early exit with return value 1</message>
    ... </test>''')
    >>> s = junit_case_from_check_case(success)
    >>> s.attrib
    {'classname': 'ex_xml_output.c:8', 'name': 'test_pass'}
    >>> len(s)
    0
    >>> f = junit_case_from_check_case(failure)
    >>> f.attrib
    {'classname': 'ex_xml_output.c:14', 'name': 'test_fail'}
    >>> len(f)
    1
    >>> f[0].attrib['message'] = 'Failure'
    >>> e = junit_case_from_check_case(error)
    >>> e.attrib
    {'classname': 'ex_xml_output.c:18', 'name': 'test_exit'}
    >>> len(e)
    1
    >>> e[0].attrib['message'] = 'Early exit with return value 1'
    """
    ns, tag = split_ns_from_tag(check_case.tag)
    result = check_case.attrib['result']
    name = check_case.find(".//{%s}id" % ns)
    classname = check_case.find(".//{%s}fn" % ns)
    message = check_case.find(".//{%s}message" % ns)
    case = ET.Element('testcase', {'name': name.text, 'classname': classname.text})
    if(result == "failure"):
        case.append(ET.Element('failure', {'message': message.text or ''}))
    if(result == "error"):
        case.append(ET.Element('error', {'message': message.text or ''}))
    return case


def junit_suite_from_check_suite(check_suite, time=None):
    """
    >>> __check_suite = ET.XML('''<suite xmlns="http://check.sourceforge.net/ns">
    ...   <title>S1</title>
    ...   <test result="success">
    ...     <path>.</path>
    ...     <fn>ex_xml_output.c:8</fn>
    ...     <id>test_pass</id>
    ...     <description>Core</description>
    ...     <message>Passed</message>
    ...   </test>
    ...   <test result="failure">
    ...     <path>.</path>
    ...     <fn>ex_xml_output.c:14</fn>
    ...     <id>test_fail</id>
    ...     <description>Core</description>
    ...     <message>Failure</message>
    ...   </test>
    ... </suite>''')
    >>> suite = junit_suite_from_check_suite(__check_suite, time="2004-08-20 12:53:32")
    >>> suite.attrib
    {'timestamp': '2004-08-20T12:53:32', 'tests': '2', 'name': 'S1'}
    >>> len(suite)
    2
    """
    ns, tag = split_ns_from_tag(check_suite.tag)
    title = check_suite.find(".//{%s}title" % ns)
    suite = ET.Element('testsuite', {'name': title.text})
    for case in check_suite.findall(".//{%s}test" % ns):
        suite.append(junit_case_from_check_case(case))
    if(time is not None):
        date = dateutil.parser.parse(time)
        suite.attrib['timestamp'] = date.isoformat()

    test_count = len(suite.findall('.//testcase'))
    suite.attrib['tests'] = str(test_count)

    return suite


def junit_etree_from_check_etree(check_etree):
    """
    >>> tree = ET.ElementTree(ET.XML(__check_test_string))
    >>> junit = junit_etree_from_check_etree(tree)
    >>> root = junit.getroot()
    >>> root.tag
    'testsuites'
    >>> root.attrib
    {'time': '0.304875'}
    >>> len(root)
    2
    >>> expected = ET.XML(__junit_test_string)
    >>> def cleanup(elem):
    ...   elem.tail = ''
    ...   if elem.text: elem.text = elem.text.strip()
    ...   [cleanup(e) for e in elem]
    >>> cleanup(expected)
    >>> ET.tostring(expected, encoding='utf8') == ET.tostring(root, encoding='utf8')
    True

    """
    check_root = check_etree.getroot()
    ns, tag = split_ns_from_tag(check_root.tag)
    duration = check_root.find('{%s}duration' % ns)
    time = check_root.find('{%s}datetime' % ns)
    root = ET.Element('testsuites', {'time': duration.text})
    for suite in check_root.findall('{%s}suite' % ns):
        root.append(junit_suite_from_check_suite(suite, time=time.text))

    return ET.ElementTree(root)


def _parse_commandline_args(arglist):
    """

    >>> input_path, output_path = _parse_commandline_args("path1 -o path2".split())
    >>> input_path
    'path1'
    >>> output_path
    'path2'
    >>> input_path, output_path = _parse_commandline_args(["path1"])
    >>> input_path
    'path1'
    >>> output_path == sys.stdout
    True

    """
    parser = argparse.ArgumentParser()
    parser.add_argument("input_path", help="The XML output file from Check")
    parser.add_argument("-o", "--output_path", help="The destination for the junit formatted XML output")
    args = parser.parse_args(arglist)
    output_path = args.output_path or sys.stdout
    return (args.input_path, output_path)


if __name__ == '__main__':
    input_path, output_path = _parse_commandline_args(sys.argv[1:])
    check_etree = ET.ElementTree(file=input_path)
    junit_tree = junit_etree_from_check_etree(check_etree)
    junit_tree.write(output_path, encoding='utf8', xml_declaration=True)
    if(junit_tree.find('.//failure') is not None or junit_tree.find('.//error') is not None):
        sys.exit(1)
    sys.exit(0)


__check_test_string = u'''<?xml version="1.0"?>
<testsuites xmlns="http://check.sourceforge.net/ns">
  <datetime>2004-08-20 12:53:32</datetime>
  <suite>
    <title>S1</title>
    <test result="success">
      <path>.</path>
      <fn>ex_xml_output.c:8</fn>
      <id>test_pass</id>
      <description>Core</description>
      <message>Passed</message>
    </test>
    <test result="failure">
      <path>.</path>
      <fn>ex_xml_output.c:14</fn>
      <id>test_fail</id>
      <description>Core</description>
      <message>Failure</message>
    </test>
    <test result="error">
      <path>.</path>
      <fn>ex_xml_output.c:18</fn>
      <id>test_exit</id>
      <description>Core</description>
      <message>Early exit with return value 1</message>
    </test>
  </suite>
  <suite>
    <title>S2</title>
    <test result="success">
      <path>.</path>
      <fn>ex_xml_output.c:26</fn>
      <id>test_pass2</id>
      <description>Core</description>
      <message>Passed</message>
    </test>
  </suite>
  <duration>0.304875</duration>
</testsuites>'''

__junit_test_string = u'''<?xml version="1.0"?>
<testsuites time="0.304875">
  <testsuite name="S1" timestamp="2004-08-20T12:53:32" tests="3">
    <testcase name="test_pass" classname="ex_xml_output.c:8" />
    <testcase name="test_fail" classname="ex_xml_output.c:14">
      <failure message="Failure" />
    </testcase>
    <testcase name="test_exit" classname="ex_xml_output.c:18">
      <error message="Early exit with return value 1" />
    </testcase>
  </testsuite>
  <testsuite name="S2" timestamp="2004-08-20T12:53:32" tests="1">
    <testcase name="test_pass2" classname="ex_xml_output.c:26" />
  </testsuite>
</testsuites>'''
